export { default as Header } from "./Header";
export { default as Footer } from "./FooterCom";
export { default as DashSidebar } from "./DashSidebar";
export { default as DashProfile } from "./DashProfile";
export { default as DashPosts } from "./DashPosts";
export { default as DashUsers } from "./DashUsers";
export {default as PrivateRoute} from "./PrivateRoute";
export {default as OnlyAdminPrivateRoute} from "./OnlyAdminPrivateRoute";
export {default as CallToAction} from "./CallToAction";
export {default as CommentSection} from "./CommentSection";
export {default as ScrollToTopComp} from "./ScrollToTopComp";
export {default as Comment} from "./Comment";